[package]
name = "perseus-error-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
perseus = { version = "0.3.2", features = ["hydrate"] }
sycamore = "0.7.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
